export const strings = {
  or: 'OR',
  home: 'Home',
  calls:'Calls',
  today: 'Today',
  log_in: 'Log in',
  contacts:'Contacts',
  password: 'Password',
  settings :'Settings',
  your_name: 'Your name',
  your_email: 'Your email',
  active_now: 'Active now',
  share_Content: 'Share Content',
  no_user_found: 'No User Found ....',
  log_in_chatBox: 'Log in to Chatbox',
  forgot_password: 'Forgot Password?',
  confirm_password: 'Confirm Password',
  existingAccount: 'Existing account?',
  getStartedSignUp: 'Sign up with mail',
  create_an_account: 'Create an account',
  write_your_message: 'Write your message',
  sign_up_with_email: 'Sign up with Email',
  welcomeLine:
    'Welcome back! Sign in using your social\naccount or email to continue us',
  signUpLine:
    'Get chatting with friends and family\ntoday by signing up for our chat app!',
  getStartedTitle: 'Connect friends easily & quickly',
  getStartedTitleMessage:
    'Our chat app is the perfect way to stay connected with friends and family.',
};
